import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import BfcacheReload from "@/components/BfcacheReload";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mapoGoldenPier = localFont({
  src: "./fonts/MapoGoldenPier.ttf",
  variable: "--font-mapo",
  weight: "400",
  display: "swap",
});

const aritaBuri = localFont({
  src: [
    { path: "./fonts/arita/AritaBuriKR-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/arita/AritaBuriKR-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/arita/AritaBuriKR-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-arita",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${mapoGoldenPier.variable} ${aritaBuri.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <BfcacheReload />
        {children}
      </body>
    </html>
  );
}
